# coding: utf-8

CAT = {
    "0": "uncategorized",
    "100": "potentialTransfer",
    "200": "check",
    "300": "atm",
    "200100": "incomeCat",
    "200110": "activityIncome",
    "200120": "replacementIncome",
    "200130": "interests",
    "200140": "dividends",
    "200150": "donationsReceived",
    "200160": "allocations",
    "200170": "rentalIncome",
    "200180": "additionalIncome",
    "200190": "retirement",
    "400100": "dailyLife",
    "400110": "supermarket",
    "400111": "tobaccoPress",
    "400112": "shoppingECommerce",
    "400120": "consumerLoan",
    "400130": "dressing",
    "400140": "pets",
    "400150": "telecom",
    "400160": "snaksAndworkMeals",
    "400170": "charity",
    "400180": "giftsOffered",
    "400190": "personalCare",
    "400200": "transportation",
    "400205": "vehiculePurchase",
    "400210": "vehiculeLoan",
    "400220": "vehiculeRental",
    "400230": "vehiculeInsurance",
    "400240": "vehiculeMaintenance",
    "400250": "vehiculeGas",
    "400260": "privateParking",
    "400270": "parkingAndToll",
    "400280": "publicTransportation",
    "400290": "taxi",
    "400300": "services",
    "400310": "post",
    "400320": "legalCounsel",
    "400330": "homeAssistance",
    "400340": "bankFees",
    "400350": "financialAdvisor",
    "400400": "kids",
    "400410": "kidsAllowance",
    "400420": "schoolRestaurant",
    "400430": "childCare",
    "400440": "schoolInsurance",
    "400450": "toysAndGifts",
    "400460": "pensionPaid",
    "400470": "kidsActivities",
    "400500": "tax",
    "400510": "incomeTax",
    "400520": "socialTax",
    "400530": "wealthTax",
    "400540": "realEstateTax",
    "400600": "health",
    "400610": "healthExpenses",
    "400620": "healthInsurance",
    "400700": "activities",
    "400710": "activityFees",
    "400720": "activityEquipments",
    "400730": "activityLessons",
    "400740": "electronicsAndMultimedia",
    "400750": "booksMoviesMusic",
    "400760": "hobbyAndPassion",
    "400800": "goingOutAndTravel",
    "400810": "restaurantsAndBars",
    "400820": "goingOutEntertainment",
    "400830": "goingOutCulture",
    "400840": "travel",
    "400850": "journey",
    "400900": "educationAndTraining",
    "400910": "tuition",
    "400920": "eduBooksAndSupplies",
    "400930": "studentLoan",
    "400940": "eduLessons",
    "401000": "homeAndRealEstate",
    "401010": "realEstateLoan",
    "401020": "rent",
    "401030": "homeCharges",
    "401040": "homeInsurance",
    "401050": "homeImprovement",
    "401060": "homeHardware",
    "401070": "water",
    "401080": "power",
    "600100": "excludeFromBudgetCat",
    "600110": "internalTransfer",
    "600120": "creditCardPayment",
    "600130": "loanCredit",
    "600140": "professionalExpenses",
    "600150": "investmentBuySell",
    "600160": "friendBorrowing",
    "600170": "savings"
}

CATNAMES = {
    "potentialTransfer": "Virements à catégoriser",
    "check": "Chèques",
    "atm": "Retraits d'espèces",
    "activityIncome": "Salaire/Revenus d'activité",
    "replacementIncome": "Revenus de remplacement",
    "interests": "Intérêts",
    "dividends": "Dividendes",
    "donationsReceived": "Cadeaux, dons reçus",
    "allocations": "Aides et allocations",
    "rentalIncome": "Revenus locatifs",
    "additionalIncome": "Revenus complémentaires",
    "retirement": "Retraite",
    "supermarket": "Alimentation, supermarché",
    "consumerLoan": "Remb. prêt conso",
    "dressing": "Habillement",
    "pets": "Animaux",
    "telecom": "Internet, TV, télécom",
    "snaksAndworkMeals": "Snacks, repas au travail",
    "charity": "Dons caritatifs",
    "giftsOffered": "Cadeaux offerts",
    "personalCare": "Coiffeur, esthétique, cosmétique, soins",
    "tobaccoPress": "Tabac/Presse",
    "shoppingECommerce": "Shopping/e-Commerce",
    "vehiculePurchase": "Achat véhicule",
    "vehiculeLoan": "Remb. prêt véhicule",
    "vehiculeRental": "Location véhicule",
    "vehiculeInsurance": "Assurance véhicule",
    "vehiculeMaintenance": "Entretien, équipements véhicules",
    "vehiculeGas": "Carburant",
    "privateParking": "Garage, parking privé",
    "parkingAndToll": "Parking, péages, PV",
    "publicTransportation": "Transports en commun",
    "taxi": "Taxi et VTC",
    "post": "Poste, courrier",
    "legalCounsel": "Conseil juridique",
    "homeAssistance": "Aide-à-domicile",
    "bankFees": "Frais bancaires",
    "financialAdvisor": "Conseil financier",
    "kidsAllowance": "Argent de poche",
    "schoolRestaurant": "Restauration scolaire",
    "childCare": "Garde d'enfants",
    "schoolInsurance": "Assurance scolaire",
    "toysAndGifts": "Jouets, cadeaux",
    "pensionPaid": "Pension versée",
    "kidsActivities": "Activités enfants",
    "incomeTax": "Impôts sur le revenu",
    "socialTax": "Contributions sociales",
    "wealthTax": "ISF",
    "realEstateTax": "Taxes foncières, d'habitation",
    "healthExpenses": "Frais, remb santé",
    "healthInsurance": "Cotis mutuelle, prévoyance",
    "activityFees": "Cotis. sports, loisirs",
    "activityEquipments": "Equipement sports, loisirs",
    "activityLessons": "Cours sports, loisirs",
    "electronicsAndMultimedia": "Electronique, multimédia",
    "booksMoviesMusic": "Musique, livres, films",
    "hobbyAndPassion": "Passion, hobby",
    "restaurantsAndBars": "Restaurants, soirées",
    "goingOutEntertainment": "Sorties détente",
    "goingOutCulture": "Sorties culturelles",
    "travel": "Voyages",
    "journey": "Avion/train/bateau...",
    "tuition": "Inscription, scolarité",
    "eduBooksAndSupplies": "Livres, fournitures (éducation)",
    "studentLoan": "Remb. prêt étudiant",
    "eduLessons": "Cours, soutien scolaire",
    "realEstateLoan": "Remb. prêt immobilier",
    "rent": "Loyer",
    "homeCharges": "Charges logement",
    "homeInsurance": "Assurance logement",
    "homeImprovement": "Travaux, déco, jardin",
    "homeHardware": "Meubles, équipement",
    "water": "Eau",
    "power": "Electricité, gaz, chauffage",
    "internalTransfer": "Virements internes",
    "creditCardPayment": "Prél. carte débit différé",
    "loanCredit": "Déblocage prêt, crédits, réserves",
    "professionalExpenses": "Notes de frais (+/-)",
    "investmentBuySell": "Achats, ventes de titres",
    "friendBorrowing": "Avances, remboursements",
    "savings": "Virements d'épargne",
    "kids": "Autres : Enfants",
    "dailyLife": "Autres : Dépenses vie courante",
    "educationAndTraining": "Autres : Education, formation",
    "health": "Autres : Santé, prévoyance",
    "homeAndRealEstate": "Autres : Logement, immobilier",
    "incomeCat": "Autres : Revenus",
    "activities": "Autres : Sports, loisirs",
    "excludeFromBudgetCat": "Autres : Hors budget",
    "services": "Autres : Services",
    "tax": "Autres : Impôts",
    "transportation": "Autres : Transports, véhicules",
    "goingOutAndTravel": "Autres : Sorties, voyages",
    "uncategorized": "Autres : A catégoriser",
    "awaiting": "Catégorisation en cours",
    "healthReimbursements": "Remb santé",
    "professionalReimbursements": "Remb notes de frais",
    "othersReimbursements": "Autres remboursements"
}
